import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic} from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { DirectionProvider } from "@/components/ui/direction";
import Providers from "@/app/providers";
import "./globals.css";
import Footer from "@/features/footer/components/footer";
import Navbar from "@/features/shared/components/navbar";

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-ibm-plex-sans-arabic",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["arabic"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RTL_LOCALES = new Set(["ar", "fa", "he", "ur"]);

function getDirection(locale: string) {
  const baseLocale = locale.toLowerCase().split("-")[0];
  return RTL_LOCALES.has(baseLocale) ? "rtl" : "ltr";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = "ar";
  const direction = getDirection(locale);

  return (
    <html
      lang={locale}
      dir={direction}
      className={`${ibmPlexSansArabic.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <DirectionProvider dir={direction} direction={direction}>
            <NextIntlClientProvider>
              <Navbar />
              {children}
              <Footer />
            </NextIntlClientProvider>
          </DirectionProvider>
        </Providers>
      </body>
    </html>
  );
}
